hikvision:
  arming:
    ips: 192.168.4.27,192.168.11.105,192.168.11.106,192.168.11.208,192.168.11.209
    ipPort: 8000
    ipUserName: admin
    ipPassword: kingxin2019
server:
  port: 50000
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
    prefix: classpath:/templates/

logging:
  level:
    root: info
