hikvision:
  arming:
    ips: 192.168.4.27
    ipPort: 8000
    ipUserName: admin
    ipPassword: password
server:
  port: 50000
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
    prefix: classpath:/templates/

logging:
  level:
    root: info
